name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Initialisation
        run: |
          MODULE_VERSION=${GITHUB_REF##*/}
          # remove prefix v when it is set
          MODULE_VERSION=${MODULE_VERSION#v}
          echo "MODULE_VERSION=${MODULE_VERSION}" >> $GITHUB_ENV
          rm -rf *-zabbix-6.4-7.0.zip *-zabbix-5.0-6.2.zip

      - name: Build release for Zabbix 5.0 and newer, up to Zabbix 6.2
        if: ${{ hashFiles('manifest.5.0.json') != '' }}
        run: |
          jq -s '.[0] * .[1]' manifest.json manifest.5.0.json > tmp.json && mv tmp.json manifest.json
          jq ".version = \"${MODULE_VERSION}\"" manifest.json > tmp.json && mv tmp.json manifest.json
          zip -r "v${MODULE_VERSION}-zabbix-5.0-6.2.zip" manifest.json Module.php public helpers actions views

      - name: Build release for Zabbix 6.4 and newer
        if: ${{ hashFiles('manifest.6.4.json') != '' }}
        run: |
          jq -s '.[0] * .[1]' manifest.json manifest.6.4.json > tmp.json && mv tmp.json manifest.json
          jq ".version = \"${MODULE_VERSION}\"" manifest.json > tmp.json && mv tmp.json manifest.json
          zip -r "v${MODULE_VERSION}-zabbix-6.4-7.0.zip" manifest.json Module.php assets helpers actions views

      - name: Generate release notes
        if: ${{ hashFiles('RELEASE_NOTES.md') != '' && hashFiles('*-zabbix-6.4-7.0.zip', '*-zabbix-5.0-6.2.zip') != '' }}
        run: |
          chmod +x .github/release-notes.sh
          .github/release-notes.sh > RELEASE.md
          cat RELEASE.md

      - name: Upload release artifacts
        uses: ncipollo/release-action@v1
        if: ${{ hashFiles('*-zabbix-6.4-7.0.zip', '*-zabbix-5.0-6.2.zip') != '' }}
        with:
          bodyFile: RELEASE.md
          artifacts: "*-zabbix-6.4-7.0.zip,*-zabbix-5.0-6.2.zip"
