name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Initialisation
        run: |
          MODULE_VERSION=${GITHUB_REF##*/}
          # remove prefix v when it is set
          MODULE_VERSION=${MODULE_VERSION#v}
          echo "MODULE_VERSION=${MODULE_VERSION}" >> $GITHUB_ENV
          echo "MODULE_NAME=$(jq -r '.id' manifest.json)" >> $GITHUB_ENV

          # install composer dependencies
          [ -f "composer.json" ] && composer install || echo "composer.json not found. Skipping composer install."

          # create release files directory
          mkdir bin

      - name: Build release for Zabbix 5.0 and newer, up to Zabbix 6.2
        if: ${{ hashFiles('manifest.5.0.json') != '' }}
        run: |
          jq -s '.[0] * .[1]' manifest.json manifest.5.0.json > tmp.json && mv tmp.json manifest.json
          jq ".version = \"${MODULE_VERSION}\"" manifest.json > tmp.json && mv tmp.json manifest.json

          # run composer build script if it is defined in composer.json exists
          [ -f "composer.json" ] && [ "$(jq -r '.scripts.build' composer.json 2>/dev/null)" != "null" ] && composer run build

          zip -r "bin/zabbix-module-${MODULE_NAME}-5.0-6.2.zip" manifest.json Module.php public helpers actions views

      - name: Build release for Zabbix 6.4 and newer
        if: ${{ hashFiles('manifest.6.4.json') != '' }}
        run: |
          jq -s '.[0] * .[1]' manifest.json manifest.6.4.json > tmp.json && mv tmp.json manifest.json
          jq ".version = \"${MODULE_VERSION}\"" manifest.json > tmp.json && mv tmp.json manifest.json

          # run composer build script if it is defined in composer.json exists
          [ -f "composer.json" ] && [ "$(jq -r '.scripts.build' composer.json 2>/dev/null)" != "null" ] && composer run build

          zip -r "bin/zabbix-module-${MODULE_NAME}-6.4-7.0.zip" manifest.json Module.php assets/css assets/js helpers actions views

      - name: Generate release notes
        if: ${{ hashFiles('RELEASE_NOTES.md') != '' && hashFiles('bin/*.zip') != '' }}
        run: |
          chmod +x .github/release-notes.sh
          .github/release-notes.sh > RELEASE.md
          cat RELEASE.md

      - name: Upload release artifacts
        uses: ncipollo/release-action@v1
        if: ${{ hashFiles('bin/*.zip') != '' }}
        with:
          bodyFile: RELEASE.md
          artifacts: "bin/*.zip"
